#syntax=docker/dockerfile:1.4

FROM python:3.10-alpine

RUN apk update && apk upgrade --no-cache
RUN adduser -D microblog

WORKDIR /home/microblog

COPY app app
COPY migrations migrations
COPY requirements requirements
COPY requirements.txt microblog.py boot.sh ./

RUN python -m venv .venv && \
    .venv/bin/pip3 install --no-cache-dir -r requirements.txt && \
    chmod +x boot.sh && \
    chown -R microblog:microblog ./

ENV FLASK_APP microblog.py
USER microblog
EXPOSE 5000

HEALTHCHECK --interval=30s --timeout=5s --start-period=10s --retries=3 \
CMD curl --fail http://localhost:5000/ || exit 1

ENTRYPOINT ["./boot.sh"]
